### ISSUE TITLE
Random insertion of characters

### ISSUE THREAD

**Issue by bisoldi** [objectos/sqlreader#50]
When streaming SQL statements from an SQL file with this library, it appears to insert characters into the SQL statement.

For example, it turned the following statement:

> INSERT INTO analyzedtoken (id, analyzedtweet_id, token_id, lang, type, value, valuecorrect, typecorrect) VALUES (971, 7419, NULL, 'en', 'ORGANIZATION', 'lions', false, false)

into

> INSERT INTO analyzedtoken (id, analyzedtweet_id, token_id, lang, type, value, valuecorrect, typecorrect) VALUES (971, 7419, NULL, 'en'y 'ORGANIZATION', 'lions', false, false)

Notice, the y after the 'en'.

Here is my code:

    private static final SqlReaderConfiguration SQLREADER_FACTORY = SqlReader.configure()
            .delimiter(';')
            .delimiterKeyword("delimiter")
            .strings('\'').escaping("''", "\\'")
            .strings('"').escaping("\"\"", "\\\"")
            .comments("--")
            .build();

    public void readSQL() {
        SqlReader sqlReader = SQLREADER_FACTORY.read(FileIngestTest.class.getClassLoader().getResourceAsStream("sqlStatements.sql"));
        List<String> statementList = sqlReader.stream().collect(Collectors.toList());
        try (Connection conn = pg.getPostgresDatabase().getConnection()) {
            Statement createSql = conn.createStatement();
            for (String statement : statementList) {
                tmp = statement;
                createSql.addBatch(statement);
            }
            
            int[] batchResult = createSql.executeBatch();
        } catch (BatchUpdateException ex) {
            LOG.error("FAILED", ex.getNextException());
        }
    }

Am I possibly configuring the factory improperly?  Any help would be appreciated, this is the only library I have been able to find to read in SQL statements.  Unfortunately, the Strings within the SQL are messy, include quotes, semicolons, etc.

**Comment by marcioendo** [comment]
At a first glance, your factory seems to be correct.

It is most likely a bug in this library. 

I cannot look into this right now, but I will try to have a look later today. 

Though something tells me it could also be an encoding issue. So, just to be sure, can you please confirm:

- what is the character encoding your JVM is running
- what is the character encoding of the file you are trying to read

If I am not mistaken, this library uses whatever the default charset is set to.

**Comment by bisoldi** [comment]
Best of my knowledge, the file is UTF-8 but I'll have to check.  Almost certain default for he JVM is UTF-8.  

I'll check both tonight. 

Thanks!

**Comment by bisoldi** [comment]
I dumped the original database into an SQL file again, this time specifying UTF-8 encoding and executed the method again, no luck.  I also printed out the System's default Charset and confirmed, it's also UTF-8.

**Comment by marcioendo** [comment]
OK, thanks for that!

I am about to start digging into this issue.

I'll try to reproduce it.

**Comment by marcioendo** [comment]
I can't reproduce the error. Test in PR #51 passes.

I'll need a failing test case. 

Would you mind providing one?

**Comment by marcioendo** [comment]
Can't reproduce.

**Comment by bisoldi** [comment]
Sorry, I tried a few variations of my SQL file, including copying and pasting specific lines into another sql file and could not reproduce the error with anything except the original file.  While I don't know what would cause this, only conclusion I have is an encoding issue.  Sorry for the trouble.

**Comment by marcioendo** [comment]
No problems. In any case, I believe it will be a good thing if the 'sqlreader' would allow to specify which Charset to use while opening/reading the file. I will put this as a TODO.
